# PostgreSQL - Docker
spring.datasource.url=jdbc:postgresql://localhost:5432/resale_platform_db
spring.datasource.username=resale_admin
spring.datasource.password=resaledb
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate - PostgreSQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

# SQL
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Images
images.dir.path=uploads/images
avatars.dir.path=uploads/avatars

# Liquibase
spring.liquibase.change-log=classpath:liquibase/db.changelog-master.yaml